version: '3.8'

services:
  # Backend: Spring Boot Application
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always  
    environment:
      # These variables allow you to switch between local MySQL or AWS RDS
      - SPRING_DATASOURCE_URL=jdbc:mysql://studentappdb.chk2s4s4gy7i.ap-northeast-1.rds.amazonaws.com:3306/student_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=12345678
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - easycrud-net


  # Frontend: React Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: always      
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://35.77.219.79:8080
    depends_on:
      - backend
    networks:
      - easycrud-net

networks:
  easycrud-net:
    driver: bridge
